# Generated by Django 6.0.2 on 2026-03-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this monitor', max_length=255)),
                ('url', models.URLField(help_text='URL to monitor', max_length=500)),
                ('check_type', models.CharField(choices=[('http', 'HTTP Status'), ('keyword', 'Keyword Search')], default='http', max_length=20)),
                ('keyword', models.CharField(blank=True, default='', help_text='Keyword to search for on the page (only for keyword check type)', max_length=255)),
                ('check_interval', models.PositiveIntegerField(default=60, help_text='Check interval in seconds')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('slow', 'Slow'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_response_time', models.FloatField(blank=True, help_text='Last response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cause', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=20)),
                ('target', models.CharField(help_text='Email address or Telegram chat ID', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved'), ('acknowledged', 'Acknowledged')], default='resolved', max_length=20)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_resolved', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('keyword_found', models.BooleanField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='monitors_ch_monitor_f64b7f_idx'), models.Index(fields=['-checked_at'], name='monitors_ch_checked_53a523_idx')],
            },
        ),
    ]
